### ISSUE TITLE
Fix gitignore

### ISSUE THREAD

**Issue by trevordmiller** [trevordmiller/nova-iterm#15]
Like what was done here so the `build/` directory is ignored, but the `build` script is not:
https://github.com/trevordmiller/nova-hyperterm/pull/21/commits/cdf86945c06444b32b0dd92203dca7a0cd6ca9e8

**Comment by scorpionhiccup** [comment]
i'm on it

**Comment by trevordmiller** [comment]
@scorpionhiccup Thanks for your interest! Sorry I shouldn't have created this story as this repo needs the `build/` directory to be commited. My bad. This same issue is valid in the other nova repos - feel free to fix it there if you'd like :) All that needs to be done is to add `build/` instead of `build` to the `.gitignore

**Comment by trevordmiller** [comment]
Looks good, but see my previous comment - I created this issue on the wrong repos; see these two instead:
https://github.com/trevordmiller/nova-colors/issues/33
https://github.com/trevordmiller/nova/issues/71
Sorry about that.

**Comment by scorpionhiccup** [comment]
Added PR to them also. Have a look :)
